# here we just set defaults of the parameters.
# for actual experiments, edit experiments.py


class Map(dict):
    """
    Example:
    m = Map({'first_name': 'Eduardo'}, last_name='Pool', age=24, sports=['Soccer'])
    """

    def __init__(self, *args, **kwargs):
        super(Map, self).__init__(*args, **kwargs)
        for arg in args:
            if isinstance(arg, dict):
                for k, v in arg.items():
                    self[k] = v

        if kwargs:
            for k, v in kwargs.items():
                self[k] = v

    def __getattr__(self, attr):
        return self.get(attr)

    def __setattr__(self, key, value):
        self.__setitem__(key, value)

    def __setitem__(self, key, value):
        super(Map, self).__setitem__(key, value)
        self.__dict__.update({key: value})

    def __delattr__(self, item):
        self.__delitem__(item)

    def __delitem__(self, key):
        super(Map, self).__delitem__(key)
        del self.__dict__[key]


default_hyp = {}

#----------- dataset -----------#
default_hyp['dataset_name'] = 'SVKITTI'
default_hyp['dataset_list_dir'] = "/projects/katefgroup/datasets/svkitti"
default_hyp['dataset_location'] = "/projects/katefgroup/datasets/svkitti/pairs0/"
default_hyp['trainset'] = 'train'
default_hyp['valset'] = 'val'
default_hyp['dataset_t'] = "%s/%s.txt" % (default_hyp['dataset_list_dir'], default_hyp['trainset'])
default_hyp['dataset_v'] = "%s/%s.txt" % (default_hyp['dataset_list_dir'], default_hyp['valset'])
default_hyp['shuffle_train'] = True
default_hyp['shuffle_val'] = True
default_hyp['h'] = 128
default_hyp['w'] = 512

#----------- net design -----------#
default_hyp['do_train'] = False
default_hyp['do_write_txt'] = False
# total_init with the autogenerated name
default_hyp['do_resume'] = False

#----------- general hypers -----------#
default_hyp['bs'] = 32
default_hyp['lr'] = 1e-6
default_hyp['max_iters'] = 10000

#----------- file reading  -----------#
default_hyp['queue_capacity'] = 100 + 3 * default_hyp['bs']

#----------- logging  -----------#
default_hyp['log_freq_t'] = 100
default_hyp['log_freq_v'] = 100
# doesn't log the graph
default_hyp['do_fast_logging'] = True

#----------- camera intrinsics  -----------#
fy = 725.0
fx = 725.0
y0 = 187.0
x0 = 620.5
scale = 0.5


# Export the default hyperparameters

def create_hyperparams():
    return Map(default_hyp)
